### ISSUE TITLE
clang: error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by hojinkangdotcom** [ryohajika/ofxSeekThermal#1]
Hello,
I tried to run the ofxSeekThermal example after installing everything, but unfortunately I got this error message:

> ld: 9 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [bin/example] Error 1
make: *** [Release] Error 2

Help would be greatly appreciated. 
Thank you!

**Comment by ryohajika** [comment]
Hi @hojinkangdotcom , I'm sorry for slow response!
Can you share me what is your computer's OS and development software?

**Comment by hojinkangdotcom** [comment]
Hello Ryo, 
thank you for your answer. Currently its macOS 11.6.1 and xcode 13.2.1
But we resolved the problem by changing the camera name to OFX_SEEK_THERMAL_CAM_PRO instead of SEEK_THERMAL_CAM_COMPACT.

Thank you!
